// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Platform.Infrastructure.Persistence;

#nullable disable

namespace Platform.Migrator.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20250502122052_AddUpdatedAtToSession")]
    partial class AddUpdatedAtToSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identities")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.Domain.Models.Identities.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailConfirmationTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("email_confirmation_token_hash");

                    b.Property<DateTimeOffset?>("EmailConfirmationTokenValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmation_token_valid_to");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token_hash");

                    b.Property<DateTimeOffset?>("PasswordResetTokenValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_valid_to");

                    b.Property<bool>("RequireMfa")
                        .HasColumnType("boolean")
                        .HasColumnName("require_mfa");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_identities");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_identities_email");

                    b.HasIndex("EmailConfirmationTokenHash")
                        .HasDatabaseName("ix_identities_email_confirmation_token_hash");

                    b.HasIndex("PasswordResetTokenHash")
                        .HasDatabaseName("ix_identities_password_reset_token_hash");

                    b.ToTable("identities", "identities");
                });

            modelBuilder.Entity("Platform.Domain.Models.Identities.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_challenge");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_login_attempts");

                    b.HasIndex("IdentityId")
                        .HasDatabaseName("ix_login_attempts_identity_id");

                    b.ToTable("login_attempts", "identities");
                });

            modelBuilder.Entity("Platform.Domain.Models.Identities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("IdentityId")
                        .HasDatabaseName("ix_sessions_identity_id");

                    b.ToTable("sessions", "identities");
                });

            modelBuilder.Entity("Platform.Domain.Models.Identities.LoginAttempt", b =>
                {
                    b.HasOne("Platform.Domain.Models.Identities.Identity", null)
                        .WithMany("LoginAttempts")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_login_attempts_identities_identity_id");

                    b.OwnsOne("Platform.Domain.Models.Identities.AuthCodeChallenge", "AuthCodeChallenge", b1 =>
                        {
                            b1.Property<Guid>("LoginAttemptId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("auth_code_challenge_created_at");

                            b1.Property<string>("HashedCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("auth_code_challenge_hashed_code");

                            b1.Property<DateTimeOffset>("ValidTo")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("auth_code_challenge_valid_to");

                            b1.HasKey("LoginAttemptId");

                            b1.ToTable("login_attempts", "identities");

                            b1.WithOwner()
                                .HasForeignKey("LoginAttemptId")
                                .HasConstraintName("fk_login_attempts_login_attempts_id");
                        });

                    b.OwnsOne("Platform.Domain.Models.Identities.TwoFactorEmailAuthenticationChallenge", "TwoFactorEmailAuthenticationChallenge", b1 =>
                        {
                            b1.Property<Guid>("LoginAttemptId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CodeHash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("two_factor_email_authentication_challenge_code_hash");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("two_factor_email_authentication_challenge_created_at");

                            b1.Property<string>("SessionTokenHash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("two_factor_email_authentication_challenge_session_token_hash");

                            b1.Property<DateTimeOffset>("ValidTo")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("two_factor_email_authentication_challenge_valid_to");

                            b1.HasKey("LoginAttemptId");

                            b1.ToTable("login_attempts", "identities");

                            b1.WithOwner()
                                .HasForeignKey("LoginAttemptId")
                                .HasConstraintName("fk_login_attempts_login_attempts_id");
                        });

                    b.Navigation("AuthCodeChallenge");

                    b.Navigation("TwoFactorEmailAuthenticationChallenge");
                });

            modelBuilder.Entity("Platform.Domain.Models.Identities.Session", b =>
                {
                    b.HasOne("Platform.Domain.Models.Identities.Identity", null)
                        .WithMany("Sessions")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_identities_identity_id");
                });

            modelBuilder.Entity("Platform.Domain.Models.Identities.Identity", b =>
                {
                    b.Navigation("LoginAttempts");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
